---
# tasks file for ansible-role-nagios-bootstrap
 - name: Add host to Nagios
   command: add_host.sh {{ monitored_server }}
   when: nagios_bootstrap_state == "present"
   
 - name: Remove host from Nagios
   command: remove_host.sh {{ monitored_server }}
   when: nagios_bootstrap_state == "absent"